name: Build & Deploy Next.js

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Docker Hub Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build Docker Image
        run: |
          # "kakaotechhackathonnews/frontend" 라는 이름으로 빌드
          docker build \
            -t kakaotechhackathonnews/frontend:latest \
            -t kakaotechhackathonnews/frontend:${{ github.sha }} \
            .

      - name: Push Docker Image
        run: |
          # latest 태그와 SHA 태그 모두 푸시
          docker push kakaotechhackathonnews/frontend:latest
          docker push kakaotechhackathonnews/frontend:${{ github.sha }}

  deploy-to-ec2:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: SSH to EC2 and deploy
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          port: ${{ secrets.EC2_PORT }}
          script: |
            # 최신 태그 사용 (필요하면 SHA 태그로도 배포 가능)
            IMAGE=kakaotechhackathonnews/frontend:latest

            echo "Stopping existing container (if any)..."
            docker stop frontend || true
            docker rm frontend || true

            echo "Pulling new Docker image: $IMAGE"
            docker pull $IMAGE

            echo "Running new container..."
            docker run -d --name frontend -p 3000:3000 $IMAGE

            echo "Deployment complete."